apiVersion: v1
kind: Service
metadata:
  name: git-proxy
  labels:
    app: git-proxy
spec:
  type: ClusterIP
  selector:
    app: git-proxy
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 8443
      targetPort: 8443
      name: https
